# Generated by Django 2.1.1 on 2018-12-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=13, unique=True)),
                ('added_by', models.CharField(default='NONE', max_length=255)),
                ('last_edited_by', models.TextField(default='NONE', max_length=255)),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255)),
                ('firm_email', models.EmailField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('bank', models.CharField(choices=[('FNB', 'FNB'), ('STB', 'STANDARD BANK'), ('NDB', 'NEDBANK'), ('ABS', 'ABSA'), ('CPT', 'CAPITEC')], default='FNB', max_length=10)),
                ('status', models.CharField(choices=[('AC', 'ACTIVE'), ('RS', 'RESIGNED'), ('FI', 'FIRED'), ('RT', 'RETIRED'), ('RC', 'RETRENCHED')], default='AC', max_length=8)),
                ('firm_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.Firm')),
            ],
        ),
    ]
