# Generated by Django 2.1.1 on 2018-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_no', models.CharField(max_length=6, unique=True)),
                ('firm_name', models.CharField(max_length=255, unique=True)),
                ('firm_contact', models.CharField(max_length=10)),
                ('firm_email', models.EmailField(max_length=255)),
            ],
        ),
    ]
